<div><label for="type">Tipo</label><select id="type" name="type" required><option value="product" @selected(old('type', $item->type ?? '') === 'product')>Producto</option><option value="instruction" @selected(old('type', $item->type ?? '') === 'instruction')>Indicacion de uso</option><option value="video" @selected(old('type', $item->type ?? '') === 'video')>Video</option><option value="story" @selected(old('type', $item->type ?? '') === 'story')>Testimonio</option></select></div>
<div><label for="title">Titulo</label><input id="title" name="title" value="{{ old('title', $item->title ?? '') }}" required></div>
<div><label for="summary">Resumen</label><textarea id="summary" name="summary" rows="2">{{ old('summary', $item->summary ?? '') }}</textarea></div>
<div><label for="body">Informacion completa</label><textarea id="body" name="body" rows="7" required>{{ old('body', $item->body ?? '') }}</textarea></div>
@if(isset($item) && $item->media_url)<div class="current-media"><span>Archivo actual</span><a href="{{ $item->media_url }}" target="_blank" rel="noopener">Ver contenido</a></div>@endif
<div><label for="media_file">Imagen o video local</label><input id="media_file" name="media_file" type="file" accept=".jpg,.jpeg,.png,.webp,.mp4,.webm"><small class="hint">Maximo 100 MB. Al subir otro archivo se reemplaza el actual.</small></div>
<div><label for="media_url">O enlace externo</label><input id="media_url" name="media_url" type="url" value="{{ old('media_url', isset($item) && str_starts_with($item->media_url ?? '', 'http') ? $item->media_url : '') }}" placeholder="https://"></div>
<div><label for="sort_order">Orden sugerido</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $item->sort_order ?? 0) }}"></div>
<div class="form-actions"><button class="button subtle" type="submit" name="action" value="draft">Guardar borrador</button><button class="button primary" type="submit" name="action" value="submit">Enviar a revision</button></div>
