<div><label for="type">Categoria</label><select id="type" name="type" required><option value="product" @selected(old('type', $item->type ?? '') === 'product')>Producto</option><option value="instruction" @selected(old('type', $item->type ?? '') === 'instruction')>Indicacion de uso</option><option value="video" @selected(old('type', $item->type ?? '') === 'video')>Video</option><option value="story" @selected(old('type', $item->type ?? '') === 'story')>Testimonio</option></select></div>
<div><label for="title">Titulo</label><input id="title" name="title" value="{{ old('title', $item->title ?? '') }}" required></div>
<div><label for="summary">Resumen</label><textarea id="summary" name="summary" rows="2">{{ old('summary', $item->summary ?? '') }}</textarea></div>
<div><label for="body">Texto principal</label><textarea id="body" name="body" rows="7" required>{{ old('body', $item->body ?? '') }}</textarea></div>
<div><label for="media_files">Archivos locales</label><input id="media_files" name="media_files[]" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.mp4,.webm"><small class="hint">Hasta 8 PDF, imagenes o videos; maximo {{ floor(config('content.max_upload_kb') / 1024) }} MB por archivo.</small></div>
<div class="fields-2"><div><label for="external_kind">Tipo de enlace</label><select id="external_kind" name="external_kind"><option value="">Sin enlace</option><option value="youtube">YouTube</option><option value="link">Otro sitio</option></select></div><div><label for="external_url">URL</label><input id="external_url" name="external_url" type="url" value="{{ old('external_url') }}" placeholder="https://"></div></div>
<div><label for="resource_notes">Descripcion o transcripcion de los recursos</label><textarea id="resource_notes" name="resource_notes" rows="5" placeholder="Describe la imagen o pega la transcripcion del video. Este texto sera consultable por el chatbot.">{{ old('resource_notes') }}</textarea></div>
<div><label for="sort_order">Orden sugerido</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $item->sort_order ?? 0) }}"></div>
<div class="form-actions"><button class="button subtle" type="submit" name="action" value="draft">Guardar borrador</button><button class="button primary" type="submit" name="action" value="submit">Enviar a revision</button></div>
